#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Photo Gallery Integration
# Project: Rita Tomforde Portfolio (Eleventy)

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Photo Gallery Integration - Spec 007"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}Node.js: $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}npm: $(npm --version)${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

# Install project dependencies
npm install

# Check if @11ty/eleventy-img is installed
if ! grep -q '@11ty/eleventy-img' package.json 2>/dev/null; then
    echo -e "${YELLOW}Installing @11ty/eleventy-img...${NC}"
    npm install @11ty/eleventy-img
fi

echo -e "${GREEN}Dependencies installed${NC}"

# ============================================
# START ELEVENTY DEV SERVER
# ============================================

echo ""
echo "Starting Eleventy development server..."

# Start development server in background
npm run dev &
DEV_PID=$!

# Wait for Eleventy to start
wait_for_service 8080 "Eleventy"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Eleventy Dev Server: http://localhost:8080/rita-tomforde/"
echo "  Gallery Page:        http://localhost:8080/rita-tomforde/gallery/"
echo ""
echo "Development Commands:"
echo "  npm run dev      - Start development server"
echo "  npm run build    - Build for production"
echo ""
echo "Process ID: $DEV_PID"
echo "To stop: kill $DEV_PID"
echo ""
