#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Project: Rita Tomforde Artist Portfolio Website

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Rita Tomforde Portfolio (11ty)"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project directory
PROJECT_DIR="/Users/yaron/rita-tomfordede"
cd "$PROJECT_DIR"

# Check Node.js version
echo ""
echo "Checking prerequisites..."
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js is not installed. Please install Node.js 18+${NC}"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    echo -e "${RED}Node.js version 18+ required. Current: $(node -v)${NC}"
    exit 1
fi
echo -e "${GREEN}Node.js $(node -v) - OK${NC}"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."
if [ ! -d "node_modules" ]; then
    npm install
else
    echo -e "${YELLOW}node_modules exists, skipping install (run 'npm install' manually if needed)${NC}"
fi

# ============================================
# START ELEVENTY DEV SERVER
# ============================================

echo ""
echo "Starting Eleventy development server..."
npm run dev &
DEV_PID=$!

# Wait for dev server to start
wait_for_service 8080 "Eleventy Dev Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  Eleventy Dev Server: http://localhost:8080"
echo ""
echo "Process IDs:"
echo "  Dev Server PID: $DEV_PID"
echo ""
echo "Commands:"
echo "  npm run dev    - Start development server"
echo "  npm run build  - Build for production"
echo ""
echo "To stop the dev server:"
echo "  kill $DEV_PID"
echo ""
echo "========================================"
